# upgrades_config.py

UPGRADES = [
    {
        'name': "Unlock Beginner's Garden",
        'cost': 0,
        'secondary_cost': 0,
        'secondary_resource': None,
        'type': 'biome',
        'unlocked': True,
        'effect': "Beginner's Garden"  # The name of the biome to unlock
    },
    {
        'name': 'Unlock Desert',
        'cost': 5,
        'secondary_cost': 0,
        'secondary_resource': None,
        'type': 'biome',
        'unlocked': False,
        'effect': 'Desert'  # The name of the biome to unlock
    },
    {
        'name': 'Unlock Tropical Forest',
        'cost': 20,
        'secondary_cost': 0,
        'secondary_resource': None,
        'type': 'biome',
        'unlocked': False,
        'effect': 'Tropical Forest'  # The name of the biome to unlock
    },
    {
        'name': 'Unlock Mountain',
        'cost': 30,
        'secondary_cost': 0,
        'secondary_resource': None,
        'type': 'biome',
        'unlocked': False,
        'effect': 'Mountain'  # The name of the biome to unlock
    },
    {
        'name': 'Unlock Swamp',
        'cost': 40,
        'secondary_cost': 0,
        'secondary_resource': None,
        'type': 'biome',
        'unlocked': False,
        'effect': 'Swamp'  # The name of the biome to unlock
    },
    {
        'name': 'Unlock Resin',
        'cost': 1,
        'secondary_cost': 0,
        'secondary_resource': None,
        'type': 'plant_part',
        'unlocked': False,
        'effect': 'resin'  # The name of the plant part to unlock
    },
    {
        'name': 'Unlock Taproot',
        'cost': 5,
        'secondary_cost': 0,
        'secondary_resource': None,
        'type': 'plant_part',
        'unlocked': False,
        'effect': 'taproot'  # The name of the plant part to unlock
    },
    {
    'name': 'Unlock Pheromones',
    'cost': 2,
    'secondary_cost': 0,
    'secondary_resource': None,
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'pheromones'  # The name of the plant part to unlock
    },
    {
    'name': 'Unlock Thorns',
    'cost': 2,
    'secondary_cost': 0,
    'secondary_resource': None,
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'thorns'  # The name of the plant part to unlock
    },
    {
    'name': 'Unlock Leaves',
    'cost': 0,
    'secondary_cost': 0,
    'secondary_resource': None,
    'type': 'plant_part',
    'unlocked': True,
    'effect': 'leaves'  # The name of the plant part to unlock
    },
    {
    'name': 'Unlock Roots',
    'cost': 0,
    'secondary_cost': 0,
    'secondary_resource': None,
    'type': 'plant_part',
    'unlocked': True,
    'effect': 'roots'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Vacuoles',
    'cost': 0,
    'secondary_cost': 0,
    'secondary_resource': None,
    'type': 'plant_part',
    'unlocked': True,
    'effect': 'vacuoles'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Desert Placeholder 1',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'silica',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderdesert1'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Desert Placeholder 2',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'silica',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderdesert2'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Desert Placeholder 3',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'silica',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderdesert3'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Desert Placeholder 4',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'silica',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderdesert4'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Desert Placeholder 5',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'silica',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderdesert5'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Desert Placeholder 6',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'silica',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderdesert6'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Desert Placeholder 7',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'silica',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderdesert7'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Desert Placeholder 8',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'silica',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderdesert8'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Desert Placeholder 9',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'silica',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderdesert9'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Desert Placeholder 10',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'silica',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderdesert10'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Tropical Forest Placeholder 1',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'tannins',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdertropicalforest1'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Tropical Forest Placeholder 2',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'tannins',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdertropicalforest2'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Tropical Forest Placeholder 3',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'tannins',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdertropicalforest3'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Tropical Forest Placeholder 4',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'tannins',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdertropicalforest4'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Tropical Forest Placeholder 5',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'tannins',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdertropicalforest5'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Tropical Forest Placeholder 6',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'tannins',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdertropicalforest6'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Tropical Forest Placeholder 7',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'tannins',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdertropicalforest7'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Tropical Forest Placeholder 8',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'tannins',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdertropicalforest8'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Tropical Forest Placeholder 9',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'tannins',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdertropicalforest9'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Tropical Forest Placeholder 10',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'tannins',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdertropicalforest10'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Mountain Placeholder 1',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'calcium',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdermountain1'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Mountain Placeholder 2',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'calcium',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdermountain2'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Mountain Placeholder 3',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'calcium',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdermountain3'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Mountain Placeholder 4',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'calcium',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdermountain4'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Mountain Placeholder 5',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'calcium',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdermountain5'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Mountain Placeholder 6',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'calcium',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdermountain1'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Mountain Placeholder 7',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'calcium',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdermountain7'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Mountain Placeholder 8',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'calcium',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdermountain8'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Mountain Placeholder 9',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'calcium',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdermountain9'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Mountain Placeholder 10',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'calcium',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdermountain10'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Swamp Placeholder 1',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'fulvic',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderswamp1'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Swamp Placeholder 2',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'fulvic',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderswamp2'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Swamp Placeholder 3',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'fulvic',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderswamp3'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Swamp Placeholder 4',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'fulvic',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderswamp4'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Swamp Placeholder 5',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'fulvic',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderswamp5'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Swamp Placeholder 6',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'fulvic',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderswamp6'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Swamp Placeholder 7',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'fulvic',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderswamp7'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Swamp Placeholder 8',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'fulvic',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderswamp8'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Swamp Placeholder 9',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'fulvic',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderswamp9'  # The name of the plant part to unlock
    },
    {'name': 'Unlock Swamp Placeholder 10',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'fulvic',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderswamp10'  # The name of the plant part to unlock
    },
]
