# upgrades_config.py

UPGRADES = [
    {
        'name': "Unlock Beginner's Garden",
        'cost': 0,
        'secondary_cost': 0,
        'secondary_resource': None,
        'type': 'biome',
        'unlocked': True,
        'effect': "Beginner's Garden",
        'cost_modifier': 0.00
    },
    {
        'name': 'Unlock Desert',
        'cost': 5,
        'secondary_cost': 0,
        'secondary_resource': None,
        'type': 'biome',
        'unlocked': False,
        'effect': 'Desert',
        'cost_modifier': 0.00
    },
    {
        'name': 'Unlock Tropical Forest',
        'cost': 20,
        'secondary_cost': 0,
        'secondary_resource': None,
        'type': 'biome',
        'unlocked': False,
        'effect': 'Tropical Forest',
        'cost_modifier': 0.00
    },
    {
        'name': 'Unlock Mountain',
        'cost': 30,
        'secondary_cost': 0,
        'secondary_resource': None,
        'type': 'biome',
        'unlocked': False,
        'effect': 'Mountain',
        'cost_modifier': 0.00
    },
    {
        'name': 'Unlock Swamp',
        'cost': 40,
        'secondary_cost': 0,
        'secondary_resource': None,
        'type': 'biome',
        'unlocked': False,
        'effect': 'Swamp',
        'cost_modifier': 0.00
    },
    {
        'name': 'Unlock Resin',
        'cost': 1,
        'secondary_cost': 0,
        'secondary_resource': None,
        'type': 'plant_part',
        'unlocked': False,
        'effect': 'resin',
        'cost_modifier': 0.00
    },
    {
        'name': 'Unlock Taproot',
        'cost': 5,
        'secondary_cost': 0,
        'secondary_resource': None,
        'type': 'plant_part',
        'unlocked': False,
        'effect': 'taproot',
        'cost_modifier': 0.00
    },
    {
    'name': 'Unlock Pheromones',
    'cost': 2,
    'secondary_cost': 0,
    'secondary_resource': None,
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'pheromones',
    'cost_modifier': 0.00
    },
    {
    'name': 'Unlock Thorns',
    'cost': 2,
    'secondary_cost': 0,
    'secondary_resource': None,
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'thorns',
    'cost_modifier': 0.00
    },
    {
    'name': 'Unlock Leaves',
    'cost': 0,
    'secondary_cost': 0,
    'secondary_resource': None,
    'type': 'plant_part',
    'unlocked': True,
    'effect': 'leaves',
    'cost_modifier': 0.00
    },
    {
    'name': 'Unlock Roots',
    'cost': 0,
    'secondary_cost': 0,
    'secondary_resource': None,
    'type': 'plant_part',
    'unlocked': True,
    'effect': 'roots',
    'cost_modifier': 0.00
    },
    {'name': 'Unlock Vacuoles',
    'cost': 0,
    'secondary_cost': 0,
    'secondary_resource': None,
    'type': 'plant_part',
    'unlocked': True,
    'effect': 'vacuoles',
    'cost_modifier': 0.00
    },
    {'name': 'Unlock Desert Placeholder 1',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'silica',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderdesert1',
    'cost_modifier': 0.05
    },
    {'name': 'Unlock Desert Placeholder 2',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'silica',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderdesert2',   
    'cost_modifier': 0.10
    },
    {'name': 'Unlock Desert Placeholder 3',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'silica',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderdesert3',   
    'cost_modifier': 0.15 
    },
    {'name': 'Unlock Desert Placeholder 4',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'silica',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderdesert4',   
    'cost_modifier': 0.20
    },
    {'name': 'Unlock Desert Placeholder 5',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'silica',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderdesert5',   
    'cost_modifier': 0.25
    },
    {'name': 'Unlock Desert Placeholder 6',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'silica',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderdesert6',   
    'cost_modifier': 0.30
    },
    {'name': 'Unlock Desert Placeholder 7',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'silica',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderdesert7',   
    'cost_modifier': 0.35
    },
    {'name': 'Unlock Desert Placeholder 8',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'silica',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderdesert8',   
    'cost_modifier': 0.40
    },
    {'name': 'Unlock Desert Placeholder 9',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'silica',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderdesert9',   
    'cost_modifier': 0.45
    },
    {'name': 'Unlock Desert Placeholder 10',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'silica',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderdesert10',
    'cost_modifier': 0.50
    },
    {'name': 'Unlock Tropical Forest Placeholder 1',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'tannins',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdertropicalforest1',   
    'cost_modifier': 0.05
    },
    {'name': 'Unlock Tropical Forest Placeholder 2',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'tannins',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdertropicalforest2',
    'cost_modifier': 0.10 
    },
    {'name': 'Unlock Tropical Forest Placeholder 3',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'tannins',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdertropicalforest3'   
    },
    {'name': 'Unlock Tropical Forest Placeholder 4',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'tannins',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdertropicalforest4',
    'cost_modifier': 0.20
    },
    {'name': 'Unlock Tropical Forest Placeholder 5',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'tannins',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdertropicalforest5',
    'cost_modifier': 0.25
    },
    {'name': 'Unlock Tropical Forest Placeholder 6',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'tannins',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdertropicalforest6',
    'cost_modifier': 0.30
    },
    {'name': 'Unlock Tropical Forest Placeholder 7',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'tannins',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdertropicalforest7',
    'cost_modifier': 0.35
    },
    {'name': 'Unlock Tropical Forest Placeholder 8',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'tannins',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdertropicalforest8',
    'cost_modifier': 0.40
    },
    {'name': 'Unlock Tropical Forest Placeholder 9',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'tannins',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdertropicalforest9',
    'cost_modifier': 0.45
    },
    {'name': 'Unlock Tropical Forest Placeholder 10',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'tannins',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdertropicalforest10',
    'cost_modifier': 0.50
    },
    {'name': 'Unlock Mountain Placeholder 1',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'calcium',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdermountain1',
    'cost_modifier': 0.05
    },
    {'name': 'Unlock Mountain Placeholder 2',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'calcium',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdermountain2',
    'cost_modifier': 0.10
    },
    {'name': 'Unlock Mountain Placeholder 3',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'calcium',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdermountain3',
    'cost_modifier': 0.15
    },
    {'name': 'Unlock Mountain Placeholder 4',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'calcium',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdermountain4',
    'cost_modifier': 0.20  
    },
    {'name': 'Unlock Mountain Placeholder 5',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'calcium',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdermountain5',
    'cost_modifier': 0.25   
    },
    {'name': 'Unlock Mountain Placeholder 6',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'calcium',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdermountain1',
    'cost_modifier': 0.30 
    },
    {'name': 'Unlock Mountain Placeholder 7',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'calcium',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdermountain7',
    'cost_modifier': 0.35 
    },
    {'name': 'Unlock Mountain Placeholder 8',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'calcium',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdermountain8',
    'cost_modifier': 0.40   
    },
    {'name': 'Unlock Mountain Placeholder 9',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'calcium',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdermountain9',
    'cost_modifier': 0.45   
    },
    {'name': 'Unlock Mountain Placeholder 10',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'calcium',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholdermountain10',
    'cost_modifier': 0.50   
    },
    {'name': 'Unlock Swamp Placeholder 1',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'fulvic',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderswamp1',
    'cost_modifier': 0.05
    },
    {'name': 'Unlock Swamp Placeholder 2',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'fulvic',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderswamp2',
    'cost_modifier': 0.10
    },
    {'name': 'Unlock Swamp Placeholder 3',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'fulvic',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderswamp3',
    'cost_modifier': 0.15   
    },
    {'name': 'Unlock Swamp Placeholder 4',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'fulvic',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderswamp4',
    'cost_modifier': 0.20   
    },
    {'name': 'Unlock Swamp Placeholder 5',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'fulvic',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderswamp5',
    'cost_modifier': 0.25   
    },
    {'name': 'Unlock Swamp Placeholder 6',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'fulvic',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderswamp6',
    'cost_modifier': 0.30   
    },
    {'name': 'Unlock Swamp Placeholder 7',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'fulvic',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderswamp7',
    'cost_modifier': 0.35   
    },
    {'name': 'Unlock Swamp Placeholder 8',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'fulvic',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderswamp8',
    'cost_modifier': 0.40   
    },
    {'name': 'Unlock Swamp Placeholder 9',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'fulvic',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderswamp9',
    'cost_modifier': 0.45   
    },
    {'name': 'Unlock Swamp Placeholder 10',
    'cost': 0,
    'secondary_cost': 1,
    'secondary_resource': 'fulvic',
    'type': 'plant_part',
    'unlocked': False,
    'effect': 'placeholderswamp10',
    'cost_modifier': 0.50   
    },
]
